### ISSUE TITLE
Champion.getName() is returning different names to the ones used in the champion names on ddragon.

### ISSUE THREAD

**Issue by JonZarate** [rithms/riot-api-java#55]
I am using this links to get champ icons:
http://ddragon.leagueoflegends.com/cdn/6.3.1/img/champion/[champ_name].png

I have problems with some names (i.e. leblanc, fiddle).The names returned are ot exactly the same, I get Fiddlesticks instead of FiddleSticks and thus I can't load the image. I tried getImage().getFull() from the champion but is returning null. 

Since this API is used in other implementations, I guess I should take the name from other place, but I don't where since the getImage() is returning a null object.

Thank you.

**Comment by rithms** [comment]
Image data shouldn't be returning null if you specified using ChampData parameters that you want it.
I think I answered your question on how to do that in this issue - https://github.com/rithms/riot-api-java/issues/51#issuecomment-186664993

If you are using **api.getDataChampionList(Region region, String locale, String version, boolean dataById, ChampData... champData)** and specifying that you want image data included,

For example - 
```java
ChampionList championList = api.getDataChampionList(Region.NA, null, null, false, ChampData.IMAGE);
```

and you are still receiving null values, something is wrong and I would ask you to provide a code example so we can look into it.
===========================================================

With that said, Ddragon doesn't name image files after the champion's **name**, it is named after champion **keys**. For many champions, name and key are the same, but for others this is not the case (i.e. The champion key for Wukong is MonkeyKing).

Thus, using the value returned from **getKey()** rather than **getName()** should solve your issue.

**Comment by JonZarate** [comment]
I also realised the names were different, my question was how to get the correct value. 
I was not using _getDataChampionList(...)_, I got the Champion from the _Game_, however, _getKey()_ did the trick. Thank you.
