### ISSUE TITLE
getSpell1 and getSpell2 

### ISSUE THREAD

**Issue by JonZarate** [rithms/riot-api-java#57]
The functions in the title return int values. However, to get their icons, I need a String.
Example. http://ddragon.leagueoflegends.com/cdn/6.3.1/img/spell/SummonerFlash.png
Those functions would return a 4 instead. How can I solve this ?

Thank you.

**Comment by Linnun** [comment]
Summoner spells are generally represented by their ID (an int value).

You can use the following method to get a list of all summoner spells. From those you can also get an Image object with the String value you are looking for.

`api.getDataSummonerSpell(id, null, null, SpellData.IMAGE)`

**Comment by rithms** [comment]
I'm unsure what you mean, but -

As Linnun said, if you want to get the name of the image for a spell, you can use the ID along with the method:

'''java 
api.getDataSummonerSpell(id, null, null, SpellData.IMAGE);
'''

If you just want to make 1 call to get all spells, you can use the method :

'''java 
api.getDataSummonerSpellList(null, null, false, SpellData.IMAGE);
'''

[SummonerSpellList](https://github.com/rithms/riot-api-java/blob/887c7896e9813a4970c90c139b5e35903d6b7683/src/main/java/net/rithms/riot/api/endpoints/static_data/dto/SummonerSpellList.java) doesn't have anything to do with cacheing repeated calls. It's just a list of ALL spells, rather than just one specific spell.

**Comment by JonZarate** [comment]
I though that would solve my problem. However, I only got the id of the spell, if I want to use the cache'ed data I can't because it uses a string as key of the map. 

Should the key be an integer since that is the info we get from the game ?

**Comment by Linnun** [comment]
`public SummonerSpellList getDataSummonerSpellList(String locale, String version, boolean dataById, SpellData... spellData) throws RiotApiException`

Use `true` as value for `dataById` to receive summoner spells by id

**Comment by rithms** [comment]
Note that the keys will still be strings, but the strings will be Spell IDs instead of Spell names.

Just thought I'd clarify.
