### ISSUE TITLE
Why no setters/mutators for Dto objects?

### ISSUE THREAD

**Issue by alex-place** [rithms/riot-api-java#69]
Hello,

Quick question why do some classes simply not have setters but do have getters? 

As far as I understand it this breaks with convention for Dto and POJO's. Also this makes it extremely hard to implement any kind of persistence or caching and creates extra requests through the api. See wikipedia entry about [Data Transfer Object's](http://en.wikipedia.org/wiki/Data_Transfer_Object) 

> Data transfer object (DTO), formerly known as value objects or VO, is a design pattern used to transfer data between software application subsystems. DTOs are often used in conjunction with data access objects to retrieve data from a database.
> 
> The difference between data transfer objects and business objects or data access objects is that a DTO does not have any behaviour except for storage and retrieval of its own data (accessors and mutators).
> 
> In a traditional EJB architecture, DTOs serve dual purposes: first, they work around the problem that entity beans are not serializable; second, they implicitly define an assembly phase where all data to be used by the view is fetched and marshalled into the DTOs before returning control to the presentation tier.

So for example to create a DAO implementation of Summoner I would have to be able to restore that object from the database using either a loaded constructor or setter methods.

Please correct me if I'm wrong as I have not used this api before and if there is an alternative please let me know. Otherwise please let me know what you think about adding setters to such methods.

**Comment by rithms** [comment]
What you said makes sense to me. If you are using the DTO directly, I can see how the lack of setters can make things difficult when implementing a DAO interface with update methods and stuff.

I think we are on the same page?

Outside of the issues you would run into with persistence and DAOs, there aren't too many reasons for these objects to have setter methods, which is why they don't have them now.

I totally understand your reasoning though, and am not against just generating setters for all of the DTOs, or at least the ones it makes most sense to do so.

Someone feel free to chime in if I'm missing something.

**Comment by alex-place** [comment]
I haven't gotten too deep into the api just yet but at a glance it would be a lot more convenient than making wrappers for all of the DTO's that might want a DAO implementation or setters for some other reason.

**Comment by jluzonpr** [comment]
When the Data you're handling is immutable, a Dto without setters makes a lot of sense. This doesn't mean you can't change the values, since you can always make a new instance with the changes you need. This does require more code to do small changes, but it also ensures that once you have a reference of an object it won't be tampered with. 

This is how Strings work in Java (with some help from the compiler to lower the boilerplate code), and it is also how many functional languages implement their collections.
